apiVersion: v1
kind: Service
metadata:
  name: {{.Values.serviceName}}
  labels: 
    app: {{.Values.name}}
    run: {{.Values.serviceName}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: {{.Values.name}}
    run: {{.Values.serviceName}}