apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: teastore
    run: teastore-db
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: teastore
    run: teastore-db
