apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels: 
    app: teastore
    run: {{.Values.name}}
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.servicePort}}
    targetPort: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: teastore
    run: {{.Values.name}}
