apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
  labels:
    app: teastore
    run: teastore-registry
spec:
  type: {{.Values.serviceType}}
  ports:
  - port: {{.Values.serviceTargetPort}}
    protocol: TCP
  selector:
    app: teastore
    run: teastore-registry
